import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export interface PdfExportOptions {
  element: HTMLElement;
  title: string;
  subject: string;
  theme: string;
  font: string;
}

export async function exportToPdf({ element, title, subject }: PdfExportOptions): Promise<boolean> {
  try {
    // Sanitize title for filename
    const sanitizedTitle = title.replace(/[^a-zA-Z0-9_-]/g, '_').substring(0, 40);
    const sanitizedSubject = subject.replace(/[^a-zA-Z0-9_-]/g, '_').substring(0, 20);
    const filename = `ReviseKaro_${sanitizedSubject}_${sanitizedTitle}.pdf`;

    // High quality canvas capture
    const canvas = await html2canvas(element, {
      scale: 2, // 2x for sharp print quality
      useCORS: true,
      logging: false,
      allowTaint: true,
      backgroundColor: null
    });

    const imgData = canvas.toDataURL('image/png');
    
    // A4 dimensions in mm: 210 x 297
    const pdf = new jsPDF('p', 'mm', 'a4');
    const pdfWidth = pdf.internal.pageSize.getWidth();
    const pdfHeight = pdf.internal.pageSize.getHeight();

    const imgWidth = pdfWidth;
    const imgHeight = (canvas.height * pdfWidth) / canvas.width;

    let heightLeft = imgHeight;
    let position = 0;

    // First page
    pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
    heightLeft -= pdfHeight;

    // Remaining pages with page numbering
    let pageNum = 1;
    while (heightLeft > 0) {
      position = heightLeft - imgHeight;
      pdf.addPage();
      pageNum++;
      pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
      heightLeft -= pdfHeight;
    }

    pdf.save(filename);
    return true;
  } catch (error) {
    console.error('Error generating PDF:', error);
    // Fallback to browser print if canvas fails
    window.print();
    return false;
  }
}

export function printNotes(): void {
  window.print();
}

export function exportAsMarkdown(note: any): string {
  let md = `# ${note.title}\n\n`;
  md += `**Subject:** ${note.subject} | **Level:** ${note.difficulty}\n`;
  md += `**Generated by ReviseKaro** - *Watch Less. Revise Better.*\n\n`;
  md += `## Introduction\n${note.introduction}\n\n`;

  if (note.sections && note.sections.length > 0) {
    md += `## Core Concepts & Notes\n\n`;
    for (const sec of note.sections) {
      md += `### ${sec.title}\n`;
      md += `${sec.content}\n\n`;
      if (sec.key_points && sec.key_points.length > 0) {
        md += `*Key Points:*\n`;
        sec.key_points.forEach((kp: string) => {
          md += `- ${kp}\n`;
        });
        md += `\n`;
      }
      if (sec.formula) {
        md += `*Formula:* \`${sec.formula}\`\n\n`;
      }
      if (sec.example) {
        md += `*Example:* ${sec.example}\n\n`;
      }
    }
  }

  if (note.formulas && note.formulas.length > 0) {
    md += `## Formulas & Equations\n\n`;
    for (const f of note.formulas) {
      md += `- **${f.name}**: \`${f.formula}\`\n`;
      if (f.where) md += `  - Where: ${f.where}\n`;
      if (f.units) md += `  - Units: ${f.units}\n`;
    }
    md += `\n`;
  }

  if (note.definitions && note.definitions.length > 0) {
    md += `## Key Definitions\n\n`;
    for (const d of note.definitions) {
      md += `- **${d.term}**: ${d.definition}\n`;
    }
    md += `\n`;
  }

  if (note.exam_important && note.exam_important.length > 0) {
    md += `## Exam Important Concepts\n\n`;
    for (const e of note.exam_important) {
      md += `- **${e.topic}** [${e.probability} Priority]: ${e.tip}\n`;
    }
    md += `\n`;
  }

  if (note.quick_revision && note.quick_revision.length > 0) {
    md += `## Quick Revision Sheet\n\n`;
    for (const q of note.quick_revision) {
      md += `- ${q}\n`;
    }
    md += `\n`;
  }

  if (note.questions && note.questions.length > 0) {
    md += `## Practice & Self-Check Questions\n\n`;
    note.questions.forEach((q: any, i: number) => {
      md += `**Q${i + 1}: ${q.question}**\n*Answer:* ${q.answer}\n\n`;
    });
  }

  if (note.final_revision) {
    md += `## Summary Note\n${note.final_revision}\n`;
  }

  return md;
}

export function exportAsPlainText(note: any): string {
  const md = exportAsMarkdown(note);
  // strip basic markdown symbols
  return md
    .replace(/#{1,6}\s?/g, '')
    .replace(/\*\*/g, '')
    .replace(/\*/g, '')
    .replace(/`{1,3}/g, '');
}
